### ISSUE TITLE
Hoppers issue

### ISSUE THREAD

**Issue by lucas2107** [VolmitSoftware/React#218]
Hoppers aren't unlocked sometimes.

React 6.0.5
Paper 1.8.8

**Comment by lucas2107** [comment]
#208

**Comment by lucas2107** [comment]
Temp fix: Reload React

**Comment by lucas2107** [comment]
Spamming: http://prntscr.com/imsspd

**Comment by cyberpwnn** [comment]
Fixed in 6.0.7

**Comment by lucas2107** [comment]
Players are saying it's not fixed and they have the same problem on big potions farms.

**Comment by cyberpwnn** [comment]
Im updating hoppers, if they arent restarting that is a spigot issue. Im not sure what else i can do to resume them.

**Comment by lucas2107** [comment]
Atm, they're locked for 30s / 1m sometimes, but they're unlocked after.

**Comment by cyberpwnn** [comment]
So it isnt a problem then?

**Comment by lucas2107** [comment]
Not fixed, still locked

**Comment by cyberpwnn** [comment]
Im not sure what to do here since i am updating the block. If it doesnt start ticking im not sure what to do here. Perhaps it was locked but never got unlocked before it was unloaded?

**Comment by lucas2107** [comment]
Mhh, when they're locked, If i'm unloading them, it do nothing :/

**Comment by lucas2107** [comment]
Closing Issue. I've this problem because there's a lot of people who was using hoppers.
